In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.shape

(5572, 2)

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
# creating new column for spam
df['spam'] = df['Category'].apply(lambda x : 1 if x =='spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
# same think with function
def spam(x):
    if x == 'spam':
        return 1
    return 0

In [8]:
df['spam'] = df.Category.apply(spam)

In [9]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X = df.Message
y = df.spam
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
X_train.shape, X_test.shape

((3733,), (1839,))

In [13]:
y_train.shape,y_test.shape

((3733,), (1839,))

In [14]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[:5]

3235                                  Yup ü not comin :-(
945     I sent my scores to sophas and i had to do sec...
5319                         Kothi print out marandratha.
5528    Its just the effect of irritation. Just ignore it
247                        I asked you to call him now ok
Name: Message, dtype: object

In [16]:
type(y_train), y_train[:4]

(pandas.core.series.Series,
 3235    0
 945     0
 5319    0
 5528    0
 Name: spam, dtype: int64)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

 # CountVectorizer helps to make BAG TO WORD model for Numeric repersentation.
# Documentation of CountVectorizer = https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [18]:
type(X_train.values)

# value : going to convert in to the numpy array

numpy.ndarray

In [19]:
v = CountVectorizer()

X_train_CountVectorizer = v.fit_transform(X_train.values)
# fit_transform is method which makes the BAG TO WORD model for X_train
X_train_CountVectorizer

<3733x7081 sparse matrix of type '<class 'numpy.int64'>'
	with 49971 stored elements in Compressed Sparse Row format>

In [20]:
# values show in to spare matrix
# converting sparce matrix into numpy array.

X_trian_np = X_train_CountVectorizer.toarray()

In [21]:
X_trian_np[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
X_trian_np.shape

(3733, 7081)

In [23]:
# 3733 email now a vector with size 7081 .

In [24]:
# vocab word
v.get_feature_names_out()[1000:1050]

array(['asleep', 'asp', 'aspects', 'ass', 'assessment', 'assistance',
       'asssssholeeee', 'assume', 'assumed', 'asthere', 'astne',
       'astrology', 'asus', 'asusual', 'at', 'ate', 'athletic', 'atlanta',
       'atlast', 'atleast', 'atm', 'attach', 'attached', 'attempt',
       'attend', 'attended', 'attraction', 'atural', 'auction',
       'audiitions', 'audition', 'audrey', 'august', 'aunt', 'auntie',
       'aunties', 'aunts', 'aunty', 'aust', 'australia', 'authorise',
       'auto', 'ava', 'availa', 'available', 'avalarr', 'avatar', 'avble',
       'ave', 'avenge'], dtype=object)

In [25]:
# size of vocab
v.get_feature_names_out().shape

(7081,)

In [26]:
# all the method we can apply with v object of CountVectorizer class
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [27]:
# see vocabulary unique words assingn with vectore. 
v.vocabulary_

{'yup': 7068,
 'not': 4414,
 'comin': 1735,
 'sent': 5511,
 'my': 4269,
 'scores': 5442,
 'to': 6329,
 'sophas': 5790,
 'and': 877,
 'had': 3007,
 'do': 2155,
 'secondary': 5467,
 'application': 934,
 'for': 2676,
 'few': 2565,
 'schools': 5436,
 'think': 6246,
 'if': 3279,
 'you': 7047,
 'are': 956,
 'thinking': 6249,
 'of': 4469,
 'applying': 937,
 'research': 5242,
 'on': 4512,
 'cost': 1834,
 'also': 848,
 'contact': 1796,
 'joke': 3500,
 'ogunrinde': 4488,
 'her': 3115,
 'school': 5435,
 'is': 3415,
 'one': 4517,
 'me': 4017,
 'the': 6218,
 'less': 3725,
 'expensive': 2471,
 'ones': 4518,
 'kothi': 3620,
 'print': 4958,
 'out': 4582,
 'marandratha': 3965,
 'its': 3435,
 'just': 3531,
 'effect': 2309,
 'irritation': 3413,
 'ignore': 3282,
 'it': 3427,
 'asked': 995,
 'call': 1453,
 'him': 3132,
 'now': 4425,
 'ok': 4493,
 'whatever': 6827,
 'juliana': 3523,
 'want': 6743,
 'hello': 3102,
 'got': 2925,
 'here': 3116,
 'st': 5880,
 'andrews': 880,
 'boy': 1330,
 'long': 3822,
 'way':

In [28]:
v.get_feature_names_out()[7068]

'yup'

In [29]:
X_trian_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
# Finding non 0 values in vectore.
np.where(X_trian_np[0] != 0)

(array([1735, 4414, 7068], dtype=int64),)

In [31]:
X_trian_np[0][1735],X_trian_np[0][4414],X_trian_np[0][7068]

(1, 1, 1)

In [32]:
X_train[:4][3235]

'Yup ü not comin :-('

In [33]:
v.get_feature_names_out()[1735],v.get_feature_names_out()[4414],v.get_feature_names_out()[7068]

('comin', 'not', 'yup')

# all set for machine learning model

In [34]:
from sklearn.naive_bayes import MultinomialNB
model =  MultinomialNB()
model.fit(X_trian_np,y_train)

MultinomialNB()

In [35]:
X_trian_np.shape

(3733, 7081)

In [36]:
# Countvectorizer for X_test
X_test_cv = v.transform(X_test)
X_test_cv = X_test_cv.toarray()
X_test_cv[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [45]:
X_test_cv.shape

(1839, 7081)

In [46]:
X_trian_np.shape

(3733, 7081)

In [37]:
prediction = model.predict(X_test_cv)
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1593
           1       0.97      0.95      0.96       246

    accuracy                           0.99      1839
   macro avg       0.98      0.97      0.98      1839
weighted avg       0.99      0.99      0.99      1839



In [39]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

email_count= v.transform(emails)
model.predict(email_count)

array([0, 1], dtype=int64)

# Pipe Line

In [40]:
# same code with piple line for reduce the time and number of lines of code

In [41]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('naive_base', MultinomialNB())
])

In [42]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('naive_base', MultinomialNB())])

In [43]:
prediction= clf.predict(X_test)

In [44]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1593
           1       0.97      0.95      0.96       246

    accuracy                           0.99      1839
   macro avg       0.98      0.97      0.98      1839
weighted avg       0.99      0.99      0.99      1839



In [47]:
X_test.shape,X_train.shape

((1839,), (3733,))

In [48]:
X_test_cv.shape,X_trian_np.shape

((1839, 7081), (3733, 7081))